#!/usr/bin/env python3
"""SnowClaw CLI — bootstrapper for running OpenClaw on Snowflake Container Services."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
from InquirerPy import inquirer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

__version__ = "0.1.0"

console = Console()


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def get_templates_dir() -> Path:
    """Return the path to the templates/ directory bundled with the CLI."""
    return Path(__file__).resolve().parent / "templates"


def find_project_root() -> Path:
    """Walk up from cwd to find the SnowClaw project root (contains .snowclaw marker)."""
    cur = Path.cwd()
    for d in [cur, *cur.parents]:
        if (d / ".snowclaw").exists():
            return d
    console.print("[red]Could not find SnowClaw project root (no .snowclaw marker found).[/red]")
    console.print("Run [cyan]snowclaw setup[/cyan] in a fresh directory to create a project.")
    sys.exit(1)


def scaffold_project(target: Path, force: bool = False) -> tuple[list[str], list[str]]:
    """Copy template files into target directory. Returns (copied, skipped) file lists."""
    templates = get_templates_dir()
    if not templates.is_dir():
        console.print(f"[red]Templates directory not found at {templates}[/red]")
        sys.exit(1)

    copied: list[str] = []
    skipped: list[str] = []

    for src in sorted(templates.rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(templates)
        dest = target / rel
        if dest.exists() and not force:
            skipped.append(str(rel))
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        copied.append(str(rel))

    # Set executable bit on shell scripts
    for sh in target.rglob("*.sh"):
        sh.chmod(sh.stat().st_mode | 0o111)

    # Create config/ directory for generated files
    (target / "config").mkdir(exist_ok=True)

    # Write .snowclaw marker
    marker = {
        "version": __version__,
        "created": datetime.now(timezone.utc).isoformat(),
    }
    (target / ".snowclaw").write_text(json.dumps(marker, indent=2) + "\n")

    return copied, skipped


def load_dotenv(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict. Ignores comments and blank lines."""
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()
    return env


def snowflake_rest_execute(
    account: str,
    pat: str,
    sql: str,
    database: str | None = None,
    schema: str | None = None,
) -> dict:
    """Execute a single SQL statement via the Snowflake REST API."""
    url = f"https://{account}.snowflakecomputing.com/api/v2/statements"
    headers = {
        "Authorization": f"Bearer {pat}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "X-Snowflake-Authorization-Token-Type": "PROGRAMMATIC_ACCESS_TOKEN",
    }
    body: dict = {"statement": sql, "timeout": 60}
    if database:
        body["database"] = database
    if schema:
        body["schema"] = schema

    resp = requests.post(url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    return resp.json()


def render_banner():
    """Print the SnowClaw welcome banner."""
    title = Text("❄  SnowClaw", style="bold cyan")
    subtitle = Text(f"v{__version__} — OpenClaw on Snowflake", style="dim")
    banner = Text.assemble(title, "\n", subtitle)
    console.print(Panel(banner, expand=False, border_style="cyan"))
    console.print()


# ---------------------------------------------------------------------------
# Config writers
# ---------------------------------------------------------------------------

def write_dotenv(root: Path, settings: dict):
    """Write .env file with all secrets."""
    lines = [
        "# SnowClaw environment variables (generated by snowclaw setup)",
        f"SNOWFLAKE_ACCOUNT={settings['account']}",
        f"SNOWFLAKE_REGISTRY_ACCOUNT={settings['registry_account']}",
        f"SNOWFLAKE_USER={settings['sf_user']}",
        f"SNOWFLAKE_TOKEN={settings['pat']}",
    ]
    if settings.get("openrouter_key"):
        lines.append(f"OPENROUTER_API_KEY={settings['openrouter_key']}")
    if settings.get("slack_bot_token"):
        lines.append(f"SLACK_BOT_TOKEN={settings['slack_bot_token']}")
    if settings.get("slack_app_token"):
        lines.append(f"SLACK_APP_TOKEN={settings['slack_app_token']}")

    (root / ".env").write_text("\n".join(lines) + "\n")
    console.print(f"  [green]✓[/green] Wrote {root / '.env'}")


def write_openclaw_config(root: Path, settings: dict):
    """Write config/openclaw.json with provider and channel config."""
    config: dict = {
        "gateway": {
            "auth": {
                "mode": "none",
            },
            "controlUi": {
                "dangerouslyAllowHostHeaderOriginFallback": True,
            },
        },
        "models": {"providers": {}},
        "channels": {},
        "agents": {"defaults": {}},
    }

    # Cortex provider (always included)
    config["models"]["providers"]["cortex"] = {
        "baseUrl": f"https://{settings['account']}.snowflakecomputing.com/api/v2/cortex/v1",
        "apiKey": "${SNOWFLAKE_TOKEN}",
        "api": "openai-completions",
        "models": [
            {
                "id": "claude-opus-4-6",
                "name": "Claude Opus 4.6",
                "contextWindow": 200000,
                "maxTokens": 128000,
            }
        ],
    }

    # OpenRouter provider (optional)
    if settings.get("enable_openrouter"):
        config["models"]["providers"]["openrouter"] = {
            "baseUrl": "https://openrouter.ai/api/v1",
            "apiKey": "${OPENROUTER_API_KEY}",
            "api": "openai-completions",
            "models": [],
        }

    # Slack channel (optional)
    if settings.get("enable_slack"):
        config["channels"]["slack"] = {
            "enabled": True,
            "mode": "socket",
            "accounts": {
                "default": {
                    "botToken": "${SLACK_BOT_TOKEN}",
                    "appToken": "${SLACK_APP_TOKEN}",
                }
            },
        }

    config_path = root / "config" / "openclaw.json"
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    console.print(f"  [green]✓[/green] Wrote {config_path}")


def write_connections_toml(root: Path, settings: dict):
    """Write config/connections.toml for Snowflake connectivity."""
    content = f"""default_connection_name = "main"

[main]
account = "{settings['account']}"
user = "{settings['sf_user']}"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "{settings['pat']}"
warehouse = "{settings.get('warehouse', 'COMPUTE_WH')}"
role = "{settings.get('role', 'SYSADMIN')}"
"""
    conn_path = root / "config" / "connections.toml"
    conn_path.write_text(content)
    console.print(f"  [green]✓[/green] Wrote {conn_path}")


# ---------------------------------------------------------------------------
# SQL object creation
# ---------------------------------------------------------------------------

# Statements from spcs/image-repo.sql, split for REST API (no USE SCHEMA).
SETUP_STATEMENTS = [
    "CREATE DATABASE IF NOT EXISTS snowclaw_db",
    "CREATE SCHEMA IF NOT EXISTS snowclaw_db.snowclaw_schema",
    "CREATE IMAGE REPOSITORY IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_repo",
    (
        "CREATE STAGE IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_state_stage "
        "ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)"
    ),
    (
        "CREATE SECRET IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_sf_token "
        "TYPE = GENERIC_STRING SECRET_STRING = 'placeholder'"
    ),
    (
        "CREATE SECRET IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_openrouter_key "
        "TYPE = GENERIC_STRING SECRET_STRING = 'placeholder'"
    ),
    (
        "CREATE SECRET IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_slack_bot_token "
        "TYPE = GENERIC_STRING SECRET_STRING = 'placeholder'"
    ),
    (
        "CREATE SECRET IF NOT EXISTS snowclaw_db.snowclaw_schema.snowclaw_slack_app_token "
        "TYPE = GENERIC_STRING SECRET_STRING = 'placeholder'"
    ),
    (
        "CREATE OR REPLACE NETWORK RULE snowclaw_db.snowclaw_schema.snowclaw_egress_rule "
        "MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ("
        "'openrouter.ai:443', 'api.slack.com:443', "
        "'wss-primary.slack.com:443', 'wss-backup.slack.com:443', "
        "'*.snowflakecomputing.com:443')"
    ),
    (
        "CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION snowclaw_external_access "
        "ALLOWED_NETWORK_RULES = (snowclaw_db.snowclaw_schema.snowclaw_egress_rule) "
        "ENABLED = TRUE"
    ),
    (
        "CREATE COMPUTE POOL IF NOT EXISTS snowclaw_pool "
        "MIN_NODES = 1 MAX_NODES = 1 INSTANCE_FAMILY = CPU_X64_S"
    ),
]


SECRET_VALUES = {
    "snowclaw_sf_token": "pat",
    "snowclaw_openrouter_key": "openrouter_key",
    "snowclaw_slack_bot_token": "slack_bot_token",
    "snowclaw_slack_app_token": "slack_app_token",
}


def run_snowflake_setup(settings: dict):
    """Create Snowflake objects via REST API."""
    account = settings["account"]
    pat = settings["pat"]

    with console.status("[bold cyan]Creating Snowflake objects..."):
        for stmt in SETUP_STATEMENTS:
            # Inject actual secret values into individual secret statements
            for secret_name, settings_key in SECRET_VALUES.items():
                if secret_name in stmt and "SECRET_STRING" in stmt:
                    value = settings.get(settings_key, "")
                    escaped = value.replace("'", "\\'") if value else ""
                    stmt = (
                        f"CREATE OR REPLACE SECRET snowclaw_db.snowclaw_schema.{secret_name} "
                        f"TYPE = GENERIC_STRING SECRET_STRING = '{escaped}'"
                    )
                    break
            try:
                snowflake_rest_execute(account, pat, stmt)
                # Show short description of what was created
                obj_match = re.search(r"(CREATE\s+\w+(?:\s+\w+)*\s+(?:IF NOT EXISTS\s+)?)([\w.]+)", stmt, re.IGNORECASE)
                label = obj_match.group(2) if obj_match else stmt[:60]
                console.print(f"  [green]✓[/green] {label}")
            except requests.HTTPError as e:
                console.print(f"  [red]✗[/red] Failed: {stmt[:80]}...")
                console.print(f"    [dim]{e}[/dim]")
                raise


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_setup(args: argparse.Namespace):
    """Interactive first-time setup wizard."""
    render_banner()
    cwd = Path.cwd()
    force = getattr(args, "force", False)

    # Refuse to scaffold inside the CLI repo itself
    cli_repo = get_templates_dir().parent
    if cwd.resolve() == cli_repo.resolve():
        console.print("[red]Cannot run setup inside the snowclaw CLI repo.[/red]")
        console.print("Create a new directory and run [cyan]snowclaw setup[/cyan] there:")
        console.print("  [dim]mkdir my-openclaw && cd my-openclaw && snowclaw setup[/dim]")
        sys.exit(1)

    # Scaffold project files if not already set up
    if (cwd / ".snowclaw").exists():
        console.print("[dim]Project already scaffolded, re-running config generation...[/dim]")
        root = cwd
    else:
        # Warn if directory is non-empty (ignoring .git)
        contents = [p for p in cwd.iterdir() if p.name != ".git"]
        if contents and not force:
            proceed = inquirer.confirm(
                message=f"Directory is not empty ({len(contents)} items). Scaffold here anyway?",
                default=False,
            ).execute()
            if not proceed:
                console.print("[dim]Aborted.[/dim]")
                return

        console.print("[bold]Scaffolding project files...[/bold]")
        copied, skipped = scaffold_project(cwd, force=force)
        for f in copied:
            console.print(f"  [green]✓[/green] {f}")
        for f in skipped:
            console.print(f"  [dim]  skipped {f} (already exists)[/dim]")
        console.print()
        root = cwd

    # --- Collect inputs ---
    account = inquirer.text(
        message="Snowflake account locator:",
        validate=lambda v: len(v.strip()) > 0,
        invalid_message="Account locator is required.",
    ).execute()

    registry_account = inquirer.text(
        message="Snowflake registry account (orgname-accountname, for SPCS image push):",
        validate=lambda v: len(v.strip()) > 0,
        invalid_message="Registry account is required for SPCS deployments.",
    ).execute()

    sf_user = inquirer.text(
        message="Snowflake username:",
        validate=lambda v: len(v.strip()) > 0,
        invalid_message="Username is required.",
    ).execute()

    pat = inquirer.secret(
        message="Programmatic access token (PAT):",
        validate=lambda v: len(v.strip()) > 0,
        invalid_message="PAT is required.",
    ).execute()

    providers = inquirer.checkbox(
        message="Model providers to enable:",
        choices=[
            {"name": "Snowflake Cortex", "value": "cortex", "enabled": True},
            {"name": "OpenRouter", "value": "openrouter", "enabled": False},
        ],
    ).execute()

    openrouter_key = ""
    if "openrouter" in providers:
        openrouter_key = inquirer.secret(
            message="OpenRouter API key:",
            validate=lambda v: len(v.strip()) > 0,
            invalid_message="API key is required when OpenRouter is enabled.",
        ).execute()

    enable_slack = inquirer.confirm(message="Enable Slack integration?", default=False).execute()

    slack_bot_token = ""
    slack_app_token = ""
    if enable_slack:
        slack_bot_token = inquirer.secret(message="Slack bot token (xoxb-...):", validate=lambda v: len(v.strip()) > 0).execute()
        slack_app_token = inquirer.secret(message="Slack app token (xapp-...):", validate=lambda v: len(v.strip()) > 0).execute()

    warehouse = inquirer.text(message="Snowflake warehouse:", default="COMPUTE_WH").execute()
    role = inquirer.text(message="Snowflake role:", default="SYSADMIN").execute()

    settings = {
        "account": account.strip(),
        "registry_account": registry_account.strip(),
        "sf_user": sf_user.strip(),
        "pat": pat.strip(),
        "enable_openrouter": "openrouter" in providers,
        "openrouter_key": openrouter_key.strip(),
        "enable_slack": enable_slack,
        "slack_bot_token": slack_bot_token.strip(),
        "slack_app_token": slack_app_token.strip(),
        "warehouse": warehouse.strip(),
        "role": role.strip(),
    }

    # --- Write config files ---
    console.print()
    console.print("[bold]Writing configuration files...[/bold]")
    write_dotenv(root, settings)
    write_openclaw_config(root, settings)
    write_connections_toml(root, settings)

    # --- Optionally create Snowflake objects ---
    console.print()
    create_objects = inquirer.confirm(
        message="Create Snowflake objects now? (database, schema, compute pool, etc.)",
        default=True,
    ).execute()

    if create_objects:
        console.print()
        try:
            run_snowflake_setup(settings)
            console.print()
            console.print("[green]Snowflake objects created successfully.[/green]")
        except Exception:
            console.print("[yellow]Some objects may not have been created. You can retry or create them manually.[/yellow]")

    # --- Summary ---
    console.print()
    console.print(Panel(
        "[bold]Setup complete![/bold]\n\n"
        "Next steps:\n"
        "  [cyan]docker compose up[/cyan]        — run locally\n"
        "  [cyan]snowclaw deploy[/cyan]          — deploy to SPCS\n",
        title="What's next",
        border_style="green",
        expand=False,
    ))


def cmd_deploy(args: argparse.Namespace):
    """Build, push, and deploy to SPCS."""
    render_banner()
    root = find_project_root()
    deploy_script = root / "scripts" / "deploy.sh"

    if not deploy_script.exists():
        console.print("[red]scripts/deploy.sh not found.[/red]")
        sys.exit(1)

    # Load .env so deploy.sh has access to SNOWFLAKE_ACCOUNT etc.
    env = {**os.environ, **load_dotenv(root / ".env")}

    console.print("[bold]Starting SPCS deployment...[/bold]")
    console.print()

    result = subprocess.run(
        ["bash", str(deploy_script)],
        env=env,
        cwd=str(root),
    )

    if result.returncode != 0:
        console.print("[red]Deployment failed.[/red]")
        sys.exit(result.returncode)

    console.print()
    console.print("[green]Deployment complete.[/green]")


def cmd_update(args: argparse.Namespace):
    """Update the OpenClaw version in the Dockerfile."""
    render_banner()
    root = find_project_root()
    dockerfile = root / "Dockerfile"
    content = dockerfile.read_text()

    # Parse current version
    match = re.search(r"ARG OPENCLAW_VERSION=(\S+)", content)
    current = match.group(1) if match else "unknown"
    console.print(f"Current OpenClaw version: [cyan]{current}[/cyan]")

    new_version = inquirer.text(
        message="New OpenClaw version (or 'latest'):",
        default="latest",
        validate=lambda v: len(v.strip()) > 0,
    ).execute().strip()

    if new_version == current:
        console.print("[dim]Version unchanged, nothing to do.[/dim]")
        return

    new_content = re.sub(
        r"ARG OPENCLAW_VERSION=\S+",
        f"ARG OPENCLAW_VERSION={new_version}",
        content,
    )
    dockerfile.write_text(new_content)
    console.print(f"[green]✓[/green] Updated Dockerfile to OpenClaw [cyan]{new_version}[/cyan]")

    redeploy = inquirer.confirm(message="Redeploy now?", default=False).execute()
    if redeploy:
        cmd_deploy(args)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="snowclaw",
        description="SnowClaw — OpenClaw on Snowflake Container Services",
    )
    parser.add_argument("--version", action="version", version=f"snowclaw {__version__}")

    sub = parser.add_subparsers(dest="command")
    setup_parser = sub.add_parser("setup", help="Interactive first-time setup wizard")
    setup_parser.add_argument("--force", action="store_true", help="Overwrite existing template files")
    sub.add_parser("deploy", help="Build, push, and deploy to SPCS")
    sub.add_parser("update", help="Update the OpenClaw version")

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    commands = {
        "setup": cmd_setup,
        "deploy": cmd_deploy,
        "update": cmd_update,
    }

    handler = commands.get(args.command or "setup")
    handler(args)


if __name__ == "__main__":
    main()
