"""Config file writers (.env, openclaw.json, connections.toml)."""

from __future__ import annotations

import json
from pathlib import Path

from snowclaw.network import CHANNEL_REGISTRY, TOOL_REGISTRY
from snowclaw.utils import console

CORTEX_MODELS = [
    {"id": "claude-sonnet-4-6", "name": "Claude Sonnet 4.6", "contextWindow": 200000, "maxTokens": 16384},
    {"id": "claude-opus-4-6", "name": "Claude Opus 4.6", "contextWindow": 200000, "maxTokens": 16384},
    {"id": "openai-gpt-5.1", "name": "GPT-5.1", "contextWindow": 1047576, "maxTokens": 16384},
]


def write_dotenv(root: Path, settings: dict):
    """Write .env file with all secrets."""
    # Preserve any existing extra vars before overwriting (vars not managed by setup)
    managed_keys: set[str] = set()  # populated below after building lines
    existing_extra: list[str] = []
    env_file = root / ".env"

    lines = [
        "# SnowClaw environment variables (generated by snowclaw setup)",
        f"SNOWCLAW_DB={settings['database']}",
        f"SNOWCLAW_SCHEMA={settings['schema']}",
        f"SNOWFLAKE_ACCOUNT={settings['account']}",
        f"SNOWFLAKE_USER={settings['sf_user']}",
        f"SNOWFLAKE_TOKEN={settings['pat']}",
    ]
    # Write env vars for all enabled channels
    for ch_key in settings.get("channels", []):
        entry = CHANNEL_REGISTRY.get(ch_key)
        if not entry:
            continue
        for cred in entry["credentials"]:
            if cred.get("inline"):
                continue
            value = settings.get(cred["env_var"], "")
            if value:
                lines.append(f"{cred['env_var']}={value}")

    # Tool credentials
    tool_credentials = settings.get("tool_credentials", {})
    for env_var, value in tool_credentials.items():
        if value:
            lines.append(f"{env_var}={value}")

    # Cortex proxy base URL
    lines.append(
        f"CORTEX_BASE_URL=https://{settings['account']}.snowflakecomputing.com/api/v2/cortex/v1"
    )

    # Collect keys managed by setup so we can preserve user-added extras
    managed_keys = {"SNOWCLAW_DB", "SNOWCLAW_SCHEMA", "SNOWFLAKE_ACCOUNT",
                    "SNOWFLAKE_USER", "SNOWFLAKE_TOKEN", "CORTEX_BASE_URL",
                    "SNOWCLAW_MASK_VARS"}
    for ch_key in settings.get("channels", []):
        entry = CHANNEL_REGISTRY.get(ch_key)
        if entry:
            for cred in entry["credentials"]:
                managed_keys.add(cred["env_var"])
    for env_var in tool_credentials:
        managed_keys.add(env_var)

    # Preserve extra vars the user added manually
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and "=" in stripped:
                key = stripped.partition("=")[0].strip()
                if key not in managed_keys:
                    existing_extra.append(stripped)
    if existing_extra:
        lines.append("")
        for extra_line in existing_extra:
            lines.append(extra_line)

    # Auto-populate SNOWCLAW_MASK_VARS from all secret env vars
    mask_vars: list[str] = []
    # Add all env vars that have values (except known config vars)
    config_only = {"SNOWCLAW_DB", "SNOWCLAW_SCHEMA", "SNOWCLAW_MASK_VARS",
                   "CORTEX_BASE_URL", "IMAGE_TAG"}
    for line_str in lines:
        if line_str.startswith("#") or "=" not in line_str:
            continue
        key = line_str.partition("=")[0].strip()
        if key in config_only or key == "SNOWFLAKE_ACCOUNT" or key == "SNOWFLAKE_USER":
            continue
        value = line_str.partition("=")[2].strip()
        if value and key not in mask_vars:
            mask_vars.append(key)
    if mask_vars:
        lines.append(f"SNOWCLAW_MASK_VARS={','.join(mask_vars)}")

    (root / ".env").write_text("\n".join(lines) + "\n")
    console.print(f"  [green]✓[/green] Wrote {root / '.env'}")


def write_openclaw_config(root: Path, settings: dict):
    """Write openclaw.json with provider and channel config."""
    config: dict = {
        "gateway": {
            "auth": {
                "mode": "none",
            },
            "controlUi": {
                "dangerouslyAllowHostHeaderOriginFallback": True,
            },
        },
        "models": {"providers": {}},
        "channels": {},
        "agents": {"defaults": {
            "model": f"cortex/{settings.get('default_model', CORTEX_MODELS[0]['id'])}",
        }},
    }

    # Cortex provider (always included)
    config["models"]["providers"]["cortex"] = {
        "baseUrl": "http://localhost:8080/v1",
        "apiKey": "${SNOWFLAKE_TOKEN}",
        "api": "openai-completions",
        "models": CORTEX_MODELS,
    }

    # Channels — generate config block for each enabled channel
    for ch_key in settings.get("channels", []):
        if ch_key == "slack":
            config["channels"]["slack"] = {
                "enabled": True,
                "mode": "socket",
                "accounts": {
                    "default": {
                        "botToken": "${SLACK_BOT_TOKEN}",
                        "appToken": "${SLACK_APP_TOKEN}",
                    }
                },
            }
        elif ch_key == "telegram":
            telegram_user_id = settings.get("TELEGRAM_USER_ID", "")
            config["channels"]["telegram"] = {
                "enabled": True,
                "botToken": "${TELEGRAM_BOT_TOKEN}",
                "dmPolicy": "allowlist",
                "allowFrom": [telegram_user_id] if telegram_user_id else [],
            }
        elif ch_key == "discord":
            discord_config: dict = {
                "enabled": True,
                "groupPolicy": "allowlist",
            }
            server_id = settings.get("DISCORD_SERVER_ID", "")
            user_id = settings.get("DISCORD_USER_ID", "")
            if server_id:
                guild_config: dict = {"requireMention": True}
                if user_id:
                    guild_config["users"] = [user_id]
                discord_config["guilds"] = {server_id: guild_config}
            config["channels"]["discord"] = discord_config

    # Brave Search tool (optional)
    if 'brave_search' in settings.get('tools', []):
        config['tools'] = {
            'web': {
                'search': {
                    'provider': 'brave',
                }
            }
        }


    config_path = root / "openclaw.json"
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    console.print(f"  [green]✓[/green] Wrote {config_path}")


def write_connections_toml(root: Path, settings: dict):
    """Write connections.toml for Snowflake connectivity."""
    content = f"""default_connection_name = "main"

[main]
account = "{settings['account']}"
user = "{settings['sf_user']}"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "{settings['pat']}"
warehouse = "{settings.get('warehouse', 'COMPUTE_WH')}"
role = "{settings.get('role', 'SYSADMIN')}"
"""
    conn_path = root / "connections.toml"
    conn_path.write_text(content)
    console.print(f"  [green]✓[/green] Wrote {conn_path}")
