"""Config file writers (.env, openclaw.json, connections.toml)."""

from __future__ import annotations

import json
from pathlib import Path

from snowclaw.network import CHANNEL_REGISTRY
from snowclaw.utils import console


def write_dotenv(root: Path, settings: dict):
    """Write .env file with all secrets."""
    lines = [
        "# SnowClaw environment variables (generated by snowclaw setup)",
        f"SNOWCLAW_DB={settings['database']}",
        f"SNOWCLAW_SCHEMA={settings['schema']}",
        f"SNOWFLAKE_ACCOUNT={settings['account']}",
        f"SNOWFLAKE_USER={settings['sf_user']}",
        f"SNOWFLAKE_TOKEN={settings['pat']}",
    ]
    # Write env vars for all enabled channels
    for ch_key in settings.get("channels", []):
        entry = CHANNEL_REGISTRY.get(ch_key)
        if not entry:
            continue
        for cred in entry["credentials"]:
            value = settings.get(cred["env_var"], "")
            if value:
                lines.append(f"{cred['env_var']}={value}")

    # Tool credentials
    tool_credentials = settings.get("tool_credentials", {})
    for env_var, value in tool_credentials.items():
        if value:
            lines.append(f"{env_var}={value}")

    (root / ".env").write_text("\n".join(lines) + "\n")
    console.print(f"  [green]✓[/green] Wrote {root / '.env'}")


def write_openclaw_config(root: Path, settings: dict):
    """Write openclaw.json with provider and channel config."""
    config: dict = {
        "gateway": {
            "auth": {
                "mode": "none",
            },
            "controlUi": {
                "dangerouslyAllowHostHeaderOriginFallback": True,
            },
        },
        "models": {"providers": {}},
        "channels": {},
        "agents": {"defaults": {}},
    }

    # Cortex provider (always included)
    config["models"]["providers"]["cortex"] = {
        "baseUrl": f"https://{settings['account']}.snowflakecomputing.com/api/v2/cortex/v1",
        "apiKey": "${SNOWFLAKE_TOKEN}",
        "api": "openai-completions",
        "models": [
            {
                "id": "claude-opus-4-6",
                "name": "Claude Opus 4.6",
                "contextWindow": 200000,
                "maxTokens": 128000,
            }
        ],
    }

    # Channels — generate config block for each enabled channel
    for ch_key in settings.get("channels", []):
        if ch_key == "slack":
            config["channels"]["slack"] = {
                "enabled": True,
                "mode": "socket",
                "accounts": {
                    "default": {
                        "botToken": "${SLACK_BOT_TOKEN}",
                        "appToken": "${SLACK_APP_TOKEN}",
                    }
                },
            }
        elif ch_key == "telegram":
            telegram_config: dict = {
                "enabled": True,
            }
            # Use allowlist if we have the user's Telegram ID, otherwise pairing
            telegram_id = settings.get("TELEGRAM_USER_ID", "")
            if telegram_id:
                telegram_config["dmPolicy"] = "allowlist"
                telegram_config["allowFrom"] = [telegram_id]
            else:
                telegram_config["dmPolicy"] = "pairing"
            config["channels"]["telegram"] = telegram_config
        elif ch_key == "discord":
            discord_config: dict = {
                "enabled": True,
                "groupPolicy": "allowlist",
            }
            server_id = settings.get("DISCORD_SERVER_ID", "")
            user_id = settings.get("DISCORD_USER_ID", "")
            if server_id:
                guild_config: dict = {"requireMention": True}
                if user_id:
                    guild_config["users"] = [user_id]
                discord_config["guilds"] = {server_id: guild_config}
            config["channels"]["discord"] = discord_config

    # Brave Search tool (optional)
    if "brave_search" in settings.get("tools", []):
        config["tools"] = {
            "web": {
                "search": {
                    "provider": "brave",
                }
            }
        }

    config_path = root / "openclaw.json"
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    console.print(f"  [green]✓[/green] Wrote {config_path}")


def write_connections_toml(root: Path, settings: dict):
    """Write connections.toml for Snowflake connectivity."""
    content = f"""default_connection_name = "main"

[main]
account = "{settings['account']}"
user = "{settings['sf_user']}"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "{settings['pat']}"
warehouse = "{settings.get('warehouse', 'COMPUTE_WH')}"
role = "{settings.get('role', 'SYSADMIN')}"
"""
    conn_path = root / "connections.toml"
    conn_path.write_text(content)
    console.print(f"  [green]✓[/green] Wrote {conn_path}")
