"""Config file writers (.env, openclaw.json, connections.toml)."""

from __future__ import annotations

import json
from pathlib import Path

from snowclaw.network import CHANNEL_REGISTRY, TOOL_REGISTRY
from snowclaw.utils import console

CORTEX_MODELS = [
    {"id": "claude-sonnet-4-6", "name": "Claude Sonnet 4.6", "contextWindow": 200000, "maxTokens": 16384},
    {"id": "claude-opus-4-6", "name": "Claude Opus 4.6", "contextWindow": 200000, "maxTokens": 16384},
    {"id": "openai-gpt-5.1", "name": "GPT-5.1", "contextWindow": 1047576, "maxTokens": 16384},
]


def write_dotenv(root: Path, settings: dict):
    """Write .env file with all secrets."""
    # Preserve any existing CUSTOM_ vars before overwriting
    existing_custom: list[str] = []
    env_file = root / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and "=" in stripped:
                key = stripped.partition("=")[0].strip()
                if key.startswith("CUSTOM_"):
                    existing_custom.append(stripped)

    lines = [
        "# SnowClaw environment variables (generated by snowclaw setup)",
        f"SNOWCLAW_DB={settings['database']}",
        f"SNOWCLAW_SCHEMA={settings['schema']}",
        f"SNOWFLAKE_ACCOUNT={settings['account']}",
        f"SNOWFLAKE_USER={settings['sf_user']}",
        f"SNOWFLAKE_TOKEN={settings['pat']}",
    ]
    # Write env vars for all enabled channels
    for ch_key in settings.get("channels", []):
        entry = CHANNEL_REGISTRY.get(ch_key)
        if not entry:
            continue
        for cred in entry["credentials"]:
            if cred.get("inline"):
                continue
            value = settings.get(cred["env_var"], "")
            if value:
                lines.append(f"{cred['env_var']}={value}")

    # Tool credentials
    tool_credentials = settings.get("tool_credentials", {})
    for env_var, value in tool_credentials.items():
        if value:
            lines.append(f"{env_var}={value}")

    # Cortex proxy base URL
    lines.append(
        f"CORTEX_BASE_URL=https://{settings['account']}.snowflakecomputing.com/api/v2/cortex/v1"
    )

    # Preserve existing CUSTOM_ vars
    lines.append("")
    lines.append("# Custom user secrets (add CUSTOM_ prefixed vars below)")
    for custom_line in existing_custom:
        lines.append(custom_line)

    # Auto-populate SNOWCLAW_MASK_VARS from all configured secret credentials
    # Collect all env var names marked secret across registries
    mask_candidates = ["SNOWFLAKE_TOKEN"]
    for registry in (CHANNEL_REGISTRY, TOOL_REGISTRY):
        for entry in registry.values():
            for cred in entry.get("credentials", []):
                if cred.get("secret") and cred["env_var"] not in mask_candidates:
                    mask_candidates.append(cred["env_var"])

    # Build a set of env vars that actually have values in this .env
    configured_vars = {settings.get("pat") and "SNOWFLAKE_TOKEN"}  # always if pat set
    for ch_key in settings.get("channels", []):
        entry = CHANNEL_REGISTRY.get(ch_key)
        if not entry:
            continue
        for cred in entry["credentials"]:
            if cred.get("secret") and settings.get(cred["env_var"]):
                configured_vars.add(cred["env_var"])
    for env_var, value in tool_credentials.items():
        if value:
            configured_vars.add(env_var)

    mask_vars = [v for v in mask_candidates if v in configured_vars]
    # Add CUSTOM_ var names to mask list
    for custom_line in existing_custom:
        key = custom_line.partition("=")[0].strip()
        if key not in mask_vars:
            mask_vars.append(key)
    if mask_vars:
        lines.append(f"SNOWCLAW_MASK_VARS={','.join(mask_vars)}")

    (root / ".env").write_text("\n".join(lines) + "\n")
    console.print(f"  [green]✓[/green] Wrote {root / '.env'}")


def write_openclaw_config(root: Path, settings: dict):
    """Write openclaw.json with provider and channel config."""
    config: dict = {
        "gateway": {
            "auth": {
                "mode": "none",
            },
            "controlUi": {
                "dangerouslyAllowHostHeaderOriginFallback": True,
            },
        },
        "models": {"providers": {}},
        "channels": {},
        "agents": {"defaults": {
            "model": f"cortex:{settings.get('default_model', CORTEX_MODELS[0]['id'])}",
        }},
    }

    # Cortex provider (always included)
    config["models"]["providers"]["cortex"] = {
        "baseUrl": "http://localhost:8080/v1",
        "apiKey": "${SNOWFLAKE_TOKEN}",
        "api": "openai-completions",
        "models": CORTEX_MODELS,
    }

    # Channels — generate config block for each enabled channel
    for ch_key in settings.get("channels", []):
        if ch_key == "slack":
            config["channels"]["slack"] = {
                "enabled": True,
                "mode": "socket",
                "accounts": {
                    "default": {
                        "botToken": "${SLACK_BOT_TOKEN}",
                        "appToken": "${SLACK_APP_TOKEN}",
                    }
                },
            }
        elif ch_key == "telegram":
            telegram_user_id = settings.get("TELEGRAM_USER_ID", "")
            config["channels"]["telegram"] = {
                "enabled": True,
                "botToken": "${TELEGRAM_BOT_TOKEN}",
                "dmPolicy": "allowlist",
                "allowFrom": [telegram_user_id] if telegram_user_id else [],
            }
        elif ch_key == "discord":
            discord_config: dict = {
                "enabled": True,
                "groupPolicy": "allowlist",
            }
            server_id = settings.get("DISCORD_SERVER_ID", "")
            user_id = settings.get("DISCORD_USER_ID", "")
            if server_id:
                guild_config: dict = {"requireMention": True}
                if user_id:
                    guild_config["users"] = [user_id]
                discord_config["guilds"] = {server_id: guild_config}
            config["channels"]["discord"] = discord_config

    # Brave Search tool (optional)
    if 'brave_search' in settings.get('tools', []):
        config['tools'] = {
            'web': {
                'search': {
                    'provider': 'brave',
                }
            }
        }


    config_path = root / "openclaw.json"
    config_path.write_text(json.dumps(config, indent=2) + "\n")
    console.print(f"  [green]✓[/green] Wrote {config_path}")


def write_connections_toml(root: Path, settings: dict):
    """Write connections.toml for Snowflake connectivity."""
    content = f"""default_connection_name = "main"

[main]
account = "{settings['account']}"
user = "{settings['sf_user']}"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token = "{settings['pat']}"
warehouse = "{settings.get('warehouse', 'COMPUTE_WH')}"
role = "{settings.get('role', 'SYSADMIN')}"
"""
    conn_path = root / "connections.toml"
    conn_path.write_text(content)
    console.print(f"  [green]✓[/green] Wrote {conn_path}")
